ECommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
] +static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path
from . views import *

urlpatterns = [
    path('index', index, name='index'),
    path('shop/<slug:slug>', product_details, name='product_details'),
]

app/models.py
from django.db import models
from ckeditor.fields import RichTextField
from .utils import generate_new_slug 
from django.urls import reverse


# Create your models here.
class Slider(models.Model):

    discount_choices = (
        ('HOT DEALS', 'HOt Deals'),
        ('NEW ARRIVALS', 'New Arrivals'),
        ('SPECIAL OFFERS', 'Special Offers'),
        ('TOP RATED', 'Top Rated'),
        ('BEST SELLER', 'Best Seller'),
    )

    # title = models.CharField(max_length=100)
    # description = models.TextField()
    brand = models.CharField(max_length=100)
    discount_deal = models.CharField(choices=discount_choices,max_length=100)
    sale = models.IntegerField()
    brand = models.CharField(max_length=200)
    discount = models.IntegerField()
    link = models.CharField(max_length=200)
    image = models.ImageField(upload_to='media/slider/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.brand

    class Meta:
        verbose_name = 'Slider'
        verbose_name_plural = 'Sliders'

class Banner(models.Model):
    image = models.ImageField(upload_to='media/banner/')
    discount_deal = models.CharField(max_length=100)
    quote = models.CharField(max_length=100)
    discont = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.quote

    class Meta:
        verbose_name = 'Banner'
        verbose_name_plural = 'Banners'

class Main_Category(models.Model):
    name = models.CharField(max_length=100)
    # image = models.ImageField(upload_to='media/main_category/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Main Category'
        verbose_name_plural = 'Main Categories'

class Category(models.Model):
    name = models.CharField(max_length=100)
    main_category = models.ForeignKey(Main_Category, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.main_category.name + " --- " + self.name  

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

class Sub_Category(models.Model):
    name = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.category.main_category.name  + " -- "+ self.category.name  + " -- " + self.name 

    class Meta:
        verbose_name = 'Subcategory'
        verbose_name_plural = 'Subcategories'

class Section(models.Model):
    name = models.CharField(max_length=100)
    # sub_category = models.ForeignKey(Sub_Category, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name 

    class Meta:
        verbose_name = 'Section'
        verbose_name_plural = 'Sections'

class Product(models.Model):
    product_name = models.CharField(max_length=100)
    slug = models.SlugField(verbose_name="post slug",unique=True,null=True,blank=True,editable=False)
    price = models.IntegerField()
    categories = models.ForeignKey(Category, on_delete=models.CASCADE)
    description = RichTextField()
    product_information = RichTextField(null=True)
    discount = models.IntegerField()
    quantity = models.IntegerField()
    availability = models.IntegerField()
    image = models.ImageField(upload_to='media/product/',blank=True,null=True)
    image_url = models.CharField(max_length=200,null=True)
    section = models.ForeignKey(Section, on_delete=models.DO_NOTHING)
    tags = models.CharField(max_length=100)
    sku = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product_name

    def save(self,*args, **kwargs):
        self.slug = generate_new_slug(self.__class__,self.product_name)
        return super().save(*args, **kwargs)

    # def get_absolute_url(self):
    #     return reverse('product_details',kwargs={'slug':self.slug}) 

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

class Product_Image(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='media/product_image/',blank=True,null=True)
    image_url = models.CharField(max_length=200,null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.product_name

    class Meta:
        verbose_name = 'Product Image'
        verbose_name_plural = 'Product Images'

class Additional_Info(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    specification = models.CharField(max_length=200)
    details = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.product_name

    class Meta:
        verbose_name = 'Additional Info'
        verbose_name_plural = 'Additional Infos'

app/views.py
from django.shortcuts import render
from django.db.models import Q
from .models import *

# Create your views here.
def index(request):
    slider_data = Slider.objects.all().order_by('-id')[0:3]
    banner_data = Banner.objects.all().order_by('-id')[0:3]
    main_categories = Main_Category.objects.all()

    product = Product.objects.filter(section__name = "Top Deal Of the Day").filter(availability__gt=0)
    context = {
        'sliders':slider_data,
        'banners':banner_data,
        'main_categories':main_categories,
        'products':product

    }
    return render(request, 'index.html',context)

def product_details(request, slug):
    product = Product.objects.get(slug=slug)
    context = {
        'product':product
    }
    return render(request, 'product_details.html',context)

templates/includes/banner.html
<!-- banner__area-start -->
{% load static %}
<section class="banner__area pt-20 pb-10">
    <div class="container">
        <div class="row">
            {% for data in banners %}
            <div class="col-xl-4 col-lg-4 col-md-6">
                <div class="banner__item p-relative w-img mb-30">
                    <div class="banner__img">
                        <a href="product-details.html"><img src="{{ data.image.url }}" alt=""></a>
                    </div>
                    <div class="banner__content">
                        <h6><a href="product-details.html">Intelligent <br> New Touch Control</a></h6>
                        <p>Discount 20% On Products</p>
                    </div>
                </div>
            </div>
            {% endfor %}
            <!-- <div class="col-xl-4 col-lg-4 col-md-6">
                <div class="banner__item p-relative mb-30 w-img">
                    <div class="banner__img">
                        <a href="product-details.html"><img src="assets/img/banner/banner-2.jpg" alt=""></a>
                    </div>
                    <div class="banner__content">
                        <h6><a href="product-details.html">On-sale <br> Best Prices</a></h6>
                        <p>Limited Time: Online Only!</p>
                    </div>
                </div>
            </div>
            <div class="col-xl-4 col-lg-4 col-md-6">
                <div class="banner__item p-relative mb-30 w-img">
                    <div class="banner__img">
                        <a href="product-details.html"><img src="assets/img/banner/banner-3.jpg" alt=""></a>
                    </div>
                    <div class="banner__content">
                        <h6><a href="product-details.html">Hot Sale <br> Super Laptops 2022 </a></h6>
                        <p>Free Shipping All Order</p>
                    </div>
                </div>
            </div> -->
        </div>
    </div>
</section>
<!-- banner__area-end -->

templates/includes/bannerarea.html
{% load static %}
<!-- banner__area-start -->
<section class="banner__area banner__area-d pb-10">
    <div class="container">
        <div class="row">
            <div class="col-xl-6 col-lg-6 col-md-12">
                <div class="banner__item p-relative w-img mb-30">
                    <div class="banner__img">
                        <a href="product-details.html"><img src="assets/img/banner/banner-4.jpg" alt=""></a>
                    </div>
                    <div class="banner__content">
                        <span>Bestseller Products</span>
                        <h6><a href="product-details.html">PC & Docking Station</a></h6>
                        <p>Discount 20% Off, Top Quality Products</p>
                    </div>
                </div>
            </div>
            <div class="col-xl-6 col-lg-6 col-md-12">
                <div class="banner__item p-relative mb-30 w-img">
                    <div class="banner__img">
                        <a href="product-details.html"><img src="assets/img/banner/banner-5.jpg" alt=""></a>
                    </div>
                    <div class="banner__content">
                        <span>Featured Products</span>
                        <h6><a href="product-details.html">Accessories iPhone</a></h6>
                        <p>Free Shipping All Order Over $99</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- banner__area-end -->

templates/includes/banneritem.html
{% load static %}
<!-- banner__area-start -->
<section class="banner__area pt-60 pb-25">
    <div class="container">
        <div class="row">
            <div class="col-xl-4 col-lg-6 col-md-12">
                <div class="banner__item p-relative w-img mb-30">
                    <div class="banner__img">
                        <a href="product-details.html"><img src="assets/img/banner/banner-6.jpg" alt=""></a>
                    </div>
                    <div class="banner__content banner__content-sd text-center">
                        <div class="banner-button mb-20">
                            <a href="product-details.html" class="st-btn">HOT DEALS</a>
                        </div>
                        <h6><a href="product-details.html">Sale 30% Off <br> Top Computer Case Gaming</a></h6>
                    </div>
                </div>
            </div>
            <div class="col-xl-4 col-lg-6 col-md-12">
                <div class="row">
                    <div class="col-md-12">
                        <div class="banner__item p-relative mb-30 w-img">
                            <div class="banner__img">
                                <a href="product-details.html"><img src="assets/img/banner/banner-7.jpg" alt=""></a>
                            </div>
                            <div class="banner__content banner__content-sd text-center">
                                <h6><a href="product-details.html">Electronic Deals</a></h6>
                                <p>Laptop, Computer, Smartphone, Gampad</p>
                                <div class="banner-button mt-20 d-none d-sm-block">
                                    <a href="product-details.html" class="st-btn-3 b-radius">Shop Deals</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="banner__item p-relative w-img mb-30">
                            <div class="banner__img">
                                <a href="product-details.html"><img src="assets/img/banner/banner-8.jpg" alt=""></a>
                            </div>
                            <div class="banner__content">
                                <h6><a href="product-details.html">Hot Products <br> Laptop Ultra 4K 16”</a>
                                </h6>
                                <p>Discount 20% On Products</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-4 col-lg-6 col-md-12">
                <div class="banner__item p-relative mb-30 w-img">
                    <div class="banner__img">
                        <a href="product-details.html"><img src="assets/img/banner/banner-9.jpg" alt=""></a>
                    </div>
                    <div class="banner__content banner__content-sd text-center">
                        <div class="banner-button mb-20">
                            <a href="product-details.html" class="st-btn">HOT DEALS</a>
                        </div>
                        <h6><a href="product-details.html">Sport Edition <br> Best Choice of The Year</a></h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- banner__area-end -->

templates/includes/featuresarea.html
{% load static %}
<!-- features__area-start -->
<section class="features__area pt-20">
    <div class="container">
        <div class="row row-cols-xxl-4 row-cols-xl-4 row-cols-lg-4 row-cols-md-2 row-cols-sm-2 row-cols-1 gx-0">
            <div class="col">
                <div class="features__item d-flex white-bg">
                    <div class="features__icon mr-20">
                        <i class="fal fa-truck"></i>
                    </div>
                    <div class="features__content">
                        <h6>FREE DELIVERY</h6>
                        <p>For all orders over $120</p>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="features__item d-flex white-bg">
                    <div class="features__icon mr-20">
                        <i class="fal fa-money-check"></i>
                    </div>
                    <div class="features__content">
                        <h6>SAFE PAYMENT</h6>
                        <p>100% secure payment</p>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="features__item d-flex white-bg">
                    <div class="features__icon mr-20">
                        <i class="fal fa-comments-alt"></i>
                    </div>
                    <div class="features__content">
                        <h6>24/7 HELP CENTER</h6>
                        <p>Delicated 24/7 support</p>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="features__item features__item-last d-flex white-bg">
                    <div class="features__icon mr-20">
                        <i class="fad fa-user-headset"></i>
                    </div>
                    <div class="features__content">
                        <h6>FRIENDLY SERVICES</h6>
                        <p>30 day satisfaction guarantee</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- features__area-end -->

templates/includes/modal.html
<!-- shop modal start -->
{% for modal_data in products %}
<div class="modal fade" id="productModalId-{{forloop.counter}}" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered product__modal" role="document">
        <div class="modal-content">
            <div class="product__modal-wrapper p-relative">
                <div class="product__modal-close p-absolute">
                    <button data-bs-dismiss="modal"><i class="fal fa-times"></i></button>
                </div>
                <div class="product__modal-inner">
                    <div class="row">
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
                            <div class="product__modal-box">
                                <div class="tab-content" id="modalTabContent">

                                    <div class="tab-pane fade show active" id="nav1" role="tabpanel"
                                        aria-labelledby="nav1-tab">
                                        <div class="product__modal-img w-img">
                                            <img src="{{modal_data.product_image_set.first.image_url}}" alt="">
                                        </div>
                                    </div>

                                    {% for image in modal_data.product_image_set.all %}
                                    <div class="tab-pane fade show" id="nav{{image.id}}" role="tabpanel"
                                        aria-labelledby="nav{{image.id}}-tab">
                                        <div class="product__modal-img w-img">
                                            <img src="{{image.image_url}}" alt="">
                                        </div>
                                    </div>
                                    {% endfor %}


                                </div>
                                <ul class="nav nav-tabs" id="modalTab" role="tablist">
                                    {% for image in modal_data.product_image_set.all %}
                                    <li class="nav-item" role="presentation">
                                        <button class="nav-link" id="nav{{image.id}}-tab" data-bs-toggle="tab"
                                            data-bs-target="#nav{{image.id}}" type="button" role="tab"
                                            aria-controls="nav{{image.id}}" aria-selected="true">
                                            <img src="{{image.image_url}}" alt="" style="height:85px; width:85px">
                                        </button>
                                    </li>
                                    {% endfor %}

                                </ul>
                            </div>
                        </div>
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
                            <div class="product__modal-content">
                                <h4><a href="product-details.html">{{modal_data.product_name}}</a></h4>
                                <div class="product__review d-sm-flex">
                                    <div class="rating rating__shop mb-10 mr-30">
                                        <ul>
                                            <li><a href="#"><i class="fal fa-star"></i></a></li>
                                            <li><a href="#"><i class="fal fa-star"></i></a></li>
                                            <li><a href="#"><i class="fal fa-star"></i></a></li>
                                            <li><a href="#"><i class="fal fa-star"></i></a></li>
                                            <li><a href="#"><i class="fal fa-star"></i></a></li>
                                        </ul>
                                    </div>
                                    <div class="product__add-review mb-15">
                                        <span>01 review</span>
                                    </div>
                                </div>
                                <div class="product__price">
                                    <span>रु {{modal_data.price}}</span>
                                </div>
                                <div class="product__modal-des mt-20 mb-15">
                                    <ul>

                                        <li>
                                            {{modal_data.product_information|safe|truncatechars:500}}</a></li>

                                        </li>

                                    </ul>
                                </div>
                                <div class="product__stock mb-20">
                                    <span class="mr-10">Availability :</span>
                                    <span>{{modal_data.availability}} in stock</span>
                                </div>
                                <div class="product__modal-form">
                                    <form action="#">
                                        <div class="pro-quan-area d-lg-flex align-items-center">
                                            <div class="product-quantity mr-20 mb-25">
                                                <div class="cart-plus-minus p-relative"><input type="text" value="1" />
                                                </div>
                                            </div>
                                            <div class="pro-cart-btn mb-25">
                                                <button class="cart-btn" type="submit">Add to cart</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                                <div class="product__stock mb-30">
                                    <ul>
                                        <li><a href="#">
                                                <span class="sku mr-10">SKU:</span>
                                                <span>{{modal_data.sku}}</span></a>
                                        </li>
                                        <li><a href="#">
                                                <span class="cat mr-10">Categories:</span>
                                                <span>{{modal_data.categories}}</span></a>
                                        </li>
                                        <li><a href="#">
                                                <span class="tag mr-10">Tags:</span>
                                                <span>{{modal_data.tags}}</span></a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
<!-- shop modal end -->

templates/includes/movingarea.html
{% load static %}
<!-- moveing-text-area-start -->
<section class="moveing-text-area">
    <div class="container">
        <div class="ovic-running">
            <div class="wrap">
                <div class="inner">
                    <p class="item">Free UK Delivery - Return Over $100.00 ( Excluding Homeware ) | Free UK
                        Collect From Store</p>
                    <p class="item">Design Week / 15% Off the website / Code: AYOSALE-2020</p>
                    <p class="item">Always iconic. Now organic. Introducing the $20 Organic Tee.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- moveing-text-area-end -->

templates/includes/newsletter.html
{% load static %}
<!-- cta-area-start -->
<section class="cta-area d-ldark-bg pt-55 pb-10">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-6">
                <div class="cta-item cta-item-d mb-30">
                    <h5 class="cta-title">Follow Us</h5>
                    <p>We make consolidating, marketing and tracking your social media website easy.</p>
                    <div class="cta-social">
                        <div class="social-icon">
                            <a href="#" class="facebook"><i class="fab fa-facebook-f"></i></a>
                            <a href="#" class="twitter"><i class="fab fa-twitter"></i></a>
                            <a href="#" class="youtube"><i class="fab fa-youtube"></i></a>
                            <a href="#" class="linkedin"><i class="fab fa-linkedin-in"></i></a>
                            <a href="#" class="rss"><i class="fas fa-rss"></i></a>
                            <a href="#" class="dribbble"><i class="fab fa-dribbble"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="cta-item mb-30">
                    <h5 class="cta-title">Sign Up To Newsletter</h5>
                    <p>Join 60.000+ subscribers and get a new discount coupon on every Saturday.</p>
                    <div class="subscribe__form">
                        <form action="#">
                            <input type="email" placeholder="Enter your email here...">
                            <button>subscribe</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="cta-item mb-30">
                    <h5 class="cta-title">Download App</h5>
                    <p>DukaMarket App is now available on App Store & Google Play. Get it now.</p>
                    <div class="cta-apps">
                        <div class="apps-store">
                            <a href="#"><img src="assets/img/brand/app_ios.png" alt=""></a>
                            <a href="#"><img src="assets/img/brand/app_android.png" alt=""></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>
<!-- cta-area-end -->

templates/includes/slider.html
{% load static %}

<!-- slider-area-start -->
<div class="slider-area">
    <div class="swiper-container slider__active">
        <div class="slider-wrapper swiper-wrapper">
            {% for data in sliders %}
            <div class="single-slider swiper-slide slider-height d-flex align-items-center"
                data-background="{{ data.image.url }}">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-5">
                            <div class="slider-content">
                                <div class="slider-top-btn" data-animation="fadeInLeft" data-delay="1.5s">
                                    <a href="product-details.html" class="st-btn b-radius">HOT DEALS{{data.brand}}</a>
                                </div>
                                <h2 data-animation="fadeInLeft" data-delay="1.7s" class="pt-15 slider-title pb-5">SALE
                                    30% OFF <br> FUTURE FOOTBALL BOOTS</h2>
                                <p class="pr-20 slider_text" data-animation="fadeInLeft" data-delay="1.9s">
                                    Discount 30% On Products & Free Shipping</p>
                                <div class="slider-bottom-btn mt-75">
                                    <a data-animation="fadeInUp" data-delay="1.15s" href="shop.html"
                                        class="st-btn-b b-radius">Discover now</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!-- /single-slider -->
            {% endfor %}
            <div class="main-slider-paginations"></div>
        </div>
    </div>
</div>
<!-- slider-area-end -->

templates/index.html
{% extends "includes/base.html" %}
{% load static %}

{% block slider %}
{% include 'includes/slider.html' %}
{% endblock %}

{% block banner %}
{% include 'includes/banner.html' %}
{% endblock %}


{% block topdealoftheday %}
{% include 'includes/topdealoftheday.html' %}
{% endblock %}

{% block topsellingproducts %}
{% include 'includes/topsellingproducts.html' %}
{% endblock %}

{% block featuresarea %}
{% include 'includes/featuresarea.html' %}
{% endblock %}

{% block bannerarea %}
{% include 'includes/bannerarea.html' %}
{% endblock %}

{% block recommended %}
{% include 'includes/recommended.html' %}
{% endblock %}

{% block brands %}
{% include 'includes/brands.html' %}
{% endblock %}

{% block newsletter %}
{% include 'includes/newsletter.html' %}
{% endblock %}

{% block topfeatured %}
{% include 'includes/topfeatured.html' %}
{% endblock %}

{% block movingarea %}
{% include 'includes/movingarea.html' %}
{% endblock %}

{% block banneritem %}
{% include 'includes/banneritem.html' %}
{% endblock %}

<!-- {% block body %}
{% endblock %} -->